<h3 style="color:darkblue">The pandas Data Structures</h3>

<b style="color:navy">NumPy ndarrays</b>
<li>array
<li>arange
<li>linspace
<li>ones
<li>zeros
<li>identity
<li>diagonal
<li>random
<li>empty
<li>repeat
<li>types
    </li>

In [83]:
import numpy as np

In [269]:
# 1D array
ar1 = np.array([0,1,2,3])
# 2D array
ar2 = np.array([[0,3,5],[2,8,7]])

In [3]:
ar1

array([0, 1, 2, 3])

In [4]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

shape and dimensions

In [5]:
print(ar2.shape)
print(ar2.ndim)

(2, 3)
2


list, arange, linspace

In [284]:
a = [1,2,3]
b = [i+2 for i in a]
c = [i+j for i,j in zip(a,b)];c

[4, 6, 8]

In [6]:
ar3 = np.arange(12); ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [286]:
ar4 = np.arange(3,10,3) # start, end, step size
ar4

array([3, 6, 9])

In [13]:
ar5 = np.linspace(1,1/4,4); ar5

array([1.  , 0.75, 0.5 , 0.25])

various functions

In [15]:
ar7 = np.ones((2,3,2)); ar7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [17]:
ar8 = np.zeros((4,2)); ar8

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
ar9 = np.eye(3); ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
ar10 = np.diag((2,1,4,6)); ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [20]:
np.random.seed(100)
ar11 = np.random.rand(3); ar11

array([0.54340494, 0.27836939, 0.42451759])

In [22]:
np.random.seed(100)
ar11 = np.random.rand(4); ar11

array([0.54340494, 0.27836939, 0.42451759, 0.84477613])

Return a new array of given shape and type, without initializing entries 

In [24]:
ar13 = np.empty((2,2)); ar13

array([[0.54340494, 0.27836939],
       [0.42451759, 0.84477613]])

In [25]:
np.array([[1,2],[6,7]])

array([[1, 2],
       [6, 7]])

In [26]:
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [27]:
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [298]:
a = np.array([[1,2],[6,7]])
b = np.array([[1,2],[3,4]])
c = [a,b]
c[0], c[1]

(array([[1, 2],
        [6, 7]]),
 array([[1, 2],
        [3, 4]]))

data types

In [31]:
ar = np.array([1,2,3,4], dtype = 'int'); ar

array([1, 2, 3, 4])

In [32]:
ar.dtype

dtype('int64')

In [33]:
ar = np.array([1,2,3,4], dtype = 'float'); ar

array([1., 2., 3., 4.])

In [34]:
ar.dtype

dtype('float64')

In [35]:
sar = np.array(['Goodbye','Welcome','Goodnight']); sar.dtype

dtype('<U9')

In [37]:
bar = np.array([True, False, True]); bar.dtype

dtype('bool')

In [38]:
f_ar = np.array([1,2,1.5])
f_ar.astype(int)

array([1, 2, 1])

<b style = "color:navy">NumPy indexing and slicing</b>

indexing

In [302]:
ar = np.arange(5); ar[0],ar[1],ar[-1]

(0, 1, 4)

In [304]:
ar[0:4:2]

array([0, 2])

In [305]:
ar[:]

array([0, 1, 2, 3, 4])

In [45]:
ar[0:3],ar[::-1]

(array([0, 1, 2]), array([4, 3, 2, 1, 0]))

In [46]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [50]:
ar[1,1],ar[:1,:]

(8, array([[2, 3, 4]]))

In [48]:
ar[::-1,::-1]

array([[13, 12, 11],
       [ 7,  8,  9],
       [ 4,  3,  2]])

In [52]:
ar[:2,:2] = np.ones((2,2)); ar

array([[ 1,  1,  4],
       [ 1,  1,  7],
       [11, 12, 13]])

slicing

In [53]:
ar = 2*np.arange(6); ar

array([ 0,  2,  4,  6,  8, 10])

In [60]:
print(ar[1:5])
print(ar[1:5:1])
print(ar[1:5:2])
print(ar[1:5:3])
print(ar[1:5:4])

[2 4 6 8]
[2 4 6 8]
[2 6]
[2 8]
[2]


In [66]:
print(ar[::1])
print(ar[::2])
print(ar[::3])
print(ar[::-1])
print(ar[::-2])
print(ar[::-3])

[ 0  2  4  6  8 10]
[0 4 8]
[0 6]
[10  8  6  4  2  0]
[10  6  2]
[10  4]


In [67]:
ar[:3]=1;ar

array([ 1,  1,  1,  6,  8, 10])

masking

In [70]:
np.random.seed(10)
ar = np.random.randint(0,25,10); ar

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [77]:
evenMask = (ar % 2 ==0); evenMask

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

<table style="width:60%">
  <tr>
    <th>Operation</th>
    <th>Name</th> 
  </tr>
  <tr>
    <td>+</td>
    <td>Addition</td> 
  </tr>
  <tr>
    <td>-</td>
    <td>Subtraction</td> 
  </tr>
  <tr>
    <td>*</td>
    <td>Multiplication</td> 
  </tr>
  <tr>
    <td>/</td>
    <td>Division</td> 
  </tr>
  <tr>
    <td>%</td>
    <td>Modulus</td> 
  </tr>
  <tr>
    <td>**</td>
    <td>Exponentiation</td> 
  </tr>
  <tr>
    <td>//</td>
    <td>Floor division</td> 
  </tr>
</table>

In [78]:
ar[evenMask]

array([ 4,  0, 16,  8,  0])

In [79]:
 ar=np.array(['Hungary','Nigeria',
              'Guatemala','',
              'Poland','',
              'Japan']); ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'],
      dtype='<U9')

In [81]:
ar[ar == '']

array(['', ''], dtype='<U9')

In [83]:
ar[ar == ''] = 'USA'; ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'],
      dtype='<U9')

In [84]:
ar = 11*np.arange(0,10); ar

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [85]:
ar[[1,3,4]]

array([11, 33, 44])

complex indexing

In [88]:
ar = np.arange(15);
ar2 = np.arange(0,-10,-1)[::-1]; 
ar, ar2

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0]))

In [89]:
ar[:10] = ar2; ar

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0, 10, 11, 12, 13, 14])

Copies and views

EX1: Uncopies 

In [90]:
ar1 = np.arange(12);
ar2 = ar1[::2];
ar1, ar2

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0,  2,  4,  6,  8, 10]))

In [91]:
ar2[1] = -1; ar1

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

EX2: Copies

In [92]:
ar = np.arange(8); ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [95]:
arc = ar[:3].copy(); arc

array([0, 1, 2])

In [96]:
arc[0] = -1; ar

array([0, 1, 2, 3, 4, 5, 6, 7])

Operations 

In [97]:
ar = np.arange(0,7)*5; ar

array([ 0,  5, 10, 15, 20, 25, 30])

In [100]:
ar = np.arange(5)**4; ar
# element-wise exponetial

array([  0,   1,  16,  81, 256])

In [104]:
ar = 3  + np.arange(0,30,3);
ar2 = np.arange(1,11);
ar, ar2, ar-ar2

(array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]))

In [105]:
ar/ar2

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [106]:
ar*ar2

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [109]:
ar = np.ones((2,2));
ar2 = 2*np.ones((2,2));
ar, ar2, ar.dot(ar2)

(array([[1., 1.],
        [1., 1.]]),
 array([[2., 2.],
        [2., 2.]]),
 array([[4., 4.],
        [4., 4.]]))

In [112]:
ar = np.arange(1,5);
ar2 = np.arange(5,1,-1);
ar, ar2, ar<ar2

(array([1, 2, 3, 4]), array([5, 4, 3, 2]), array([ True,  True, False, False]))

In [113]:
l1 = np.array([True, False, True, False]);
l2 = np.array([False,False,True,False]);
np.logical_and(l1,l2)

array([False, False,  True, False])

In [114]:
ar = np.array([np.pi, np.pi/2]); np.sin(ar)

array([1.2246468e-16, 1.0000000e+00])

In [117]:
ar = np.array([[1,2,3],[4,5,6]]); 
ar, ar.T, np.transpose(ar)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [2]:
ar = np.arange(0,6);
ar2 = np.array([0,1,2,3,4,5]);
np.array_equal(ar,ar2)

True

In [3]:
np.all(ar==ar2)

True

In [4]:
np.any(ar==ar2)

True

In [5]:
ar = np.arange(1,5); ar.prod()

24

In [6]:
ar.sum()

10

In [7]:
ar.cumsum()

array([ 1,  3,  6, 10])

In [124]:
ar = np.array([np.arange(1,6), np.arange(1,6)]); ar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [126]:
np.prod(ar, axis=0),
np.prod(ar, axis=1)

array([120, 120])

Statistical operators

In [8]:
ar = np.array([[2,3,4],[5,6,7],[8,9,10]]); ar.sum()

54

In [16]:
ar

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [17]:
ar.mean(axis=1)

array([3., 6., 9.])

In [13]:
np.median(ar)

6.0

In [131]:
np.random.seed(10)
ar = np.random.randint(0,10,size=(4,5)); ar

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0],
       [4, 6, 8, 1, 8]])

In [140]:
ar.cumsum(axis=0), ar.cumsum(axis=1)

(array([[ 9,  4,  0,  1,  9],
        [ 9,  5,  8, 10,  9],
        [17, 11, 12, 13,  9],
        [21, 17, 20, 14, 17]]),
 array([[ 9, 13, 13, 14, 23],
        [ 0,  1,  9, 18, 18],
        [ 8, 14, 18, 21, 21],
        [ 4, 10, 18, 19, 27]]))

In [133]:
ar.mean(), ar.std()

(4.45, 3.427462618322773)

In [137]:
ar.var(axis=0)

array([12.6875,  4.1875, 11.    , 10.75  , 18.1875])

In [138]:
ar.cumsum()

array([ 9, 13, 13, 14, 23, 23, 24, 32, 41, 41, 49, 55, 59, 62, 62, 66, 72,
       80, 81, 89])

Logical operators

In [142]:
np.random.seed(100);
ar = np.random.randint(1,10, size=(4,4)); ar

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [143]:
np.any((ar%7)==0)

False

In [144]:
np.all(ar<11)

True

Broadcasting

In [147]:
ar = np.ones([3,2]);
ar2 = np.array([2,3]);
ar, ar2, ar+ar2

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([2, 3]),
 array([[3., 4.],
        [3., 4.],
        [3., 4.]]))

In [148]:
ar = np.array([[23,24,25]]); ar

array([[23, 24, 25]])

In [149]:
ar.T

array([[23],
       [24],
       [25]])

In [150]:
ar.T + ar

array([[46, 47, 48],
       [47, 48, 49],
       [48, 49, 50]])

Array shape manipulation

In [152]:
ar =  np.array([np.arange(1,6), np.arange(10,15)]); ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [153]:
ar.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [154]:
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [156]:
ar = np.arange(1,16); 
ar, ar.reshape(3,5)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]))

In [158]:
ar = np.arange(5);
ar.resize(8,); ar

array([0, 1, 2, 3, 4, 0, 0, 0])

In [162]:
ar = np.arange(5); 
ar, np.resize(ar,(8,))

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4, 0, 1, 2]))

In [163]:
ar = np.array([14,15,16]); ar.shape

(3,)

In [164]:
ar = ar[:, np.newaxis];
ar.shape, ar

((3, 1),
 array([[14],
        [15],
        [16]]))

Array sorting

In [18]:
ar = np.array([[3,2],[10,-1]]); ar

array([[ 3,  2],
       [10, -1]])

In [168]:
ar.sort(axis=1); ar

array([[ 2,  3],
       [-1, 10]])

In [169]:
ar.sort(axis=0);ar

array([[-1,  3],
       [ 2, 10]])

<h4 style="color:navy">Data structures in pandas</h4>
<li>Series
<li>DataFrame
<li>Panel
</li>

In [86]:
import pandas as pd

Series

In [24]:
np.random.seed(100)
ser = pd.Series(np.random.rand(7)); ser

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
dtype: float64

In [25]:
import calendar as cal

In [95]:
monthNames = [cal.month_name[i] for i in np.arange(1,6)];
months = pd.Series(np.arange(1,6), index=monthNames);
months

January     1
February    2
March       3
April       4
May         5
dtype: int64

In [175]:
monthNames

['January', 'February', 'March', 'April', 'May']

In [176]:
months.index

Index(['January', 'February', 'March', 'April', 'May'], dtype='object')

In [33]:
months.index.tolist()

['January', 'February', 'March', 'April', 'May']

dictionary

In [178]:
country = ['US', 'UK', 'Germany', 'Mexico', 'Nigeria', 'China', 'Japan']
currency = ['dollar', 'pond', 'euro', 'peso', 'naira', 'yuan', 'yen']

In [180]:
currDict = dict(zip(country,currency)); currDict

{'US': 'dollar',
 'UK': 'pond',
 'Germany': 'euro',
 'Mexico': 'peso',
 'Nigeria': 'naira',
 'China': 'yuan',
 'Japan': 'yen'}

In [181]:
currSeries = pd.Series(currDict); currSeries

US         dollar
UK           pond
Germany      euro
Mexico       peso
Nigeria     naira
China        yuan
Japan         yen
dtype: object

In [93]:
stockPrices = {'GOOG':1180.97,'FB':62.57,
               'TWTR': 64.50, 'AMZN':358.69,
               'AAPL':500.6}
stockPriceSeries = pd.Series(stockPrices,
                             index=['GOOG','FB','YHOO','TWTR','AMZN','AAPL'],
                             name='stockPrices');
stockPriceSeries

GOOG    1180.97
FB        62.57
YHOO        NaN
TWTR      64.50
AMZN     358.69
AAPL     500.60
Name: stockPrices, dtype: float64

In [201]:
dogSeries=pd.Series('chihuahua',
                    index=['breed','countryOfOrigin',
                           'name', 'gender']);
dogSeries

breed              chihuahua
countryOfOrigin    chihuahua
name               chihuahua
gender             chihuahua
dtype: object

In [202]:
dogSeries=pd.Series('pekingese'); dogSeries

0    pekingese
dtype: object

In [203]:
type(dogSeries)

pandas.core.series.Series

Series Assignment

In [204]:
currDict['China']

'yuan'

In [206]:
stockPriceSeries['GOOG']=1200.0; stockPriceSeries

GOOG    1200.00
FB        62.57
YHOO        NaN
TWTR      64.50
AMZN     358.69
AAPL     500.60
Name: stockPrices, dtype: float64

In [37]:
stockPriceSeries.get('MSFT',np.nan)

nan

Series Slicing

In [211]:
stockPriceSeries[:4]

GOOG    1200.00
FB        62.57
YHOO        NaN
TWTR      64.50
Name: stockPrices, dtype: float64

In [212]:
stockPriceSeries[stockPriceSeries > 100]

GOOG    1200.00
AMZN     358.69
AAPL     500.60
Name: stockPrices, dtype: float64

Series Operations

In [215]:
np.mean(stockPriceSeries), stockPriceSeries.mean()

(437.27200000000005, 437.27200000000005)

In [216]:
np.std(stockPriceSeries), stockPriceSeries.std()

(417.4446361087899, 466.7172915909588)

In [217]:
ser

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
dtype: float64

In [218]:
ser*ser

0    0.295289
1    0.077490
2    0.180215
3    0.713647
4    0.000022
5    0.014779
6    0.449904
dtype: float64

In [219]:
np.sqrt(ser)

0    0.737160
1    0.527607
2    0.651550
3    0.919117
4    0.068694
5    0.348668
6    0.818993
dtype: float64

In [221]:
ser[1:], ser[:-2], ser[1:]+ser[:-2]

(1    0.278369
 2    0.424518
 3    0.844776
 4    0.004719
 5    0.121569
 6    0.670749
 dtype: float64,
 0    0.543405
 1    0.278369
 2    0.424518
 3    0.844776
 4    0.004719
 dtype: float64,
 0         NaN
 1    0.556739
 2    0.849035
 3    1.689552
 4    0.009438
 5         NaN
 6         NaN
 dtype: float64)

DataFrame 

In [91]:
stockSummaries={
    'AMZN': pd.Series([346.15,0.59,459,0.52,589.8,158.88],
                      index=['Closing price','EPS',
                             'Shares Outstanding(M)',
                             'Beta', 'P/E','Market Cap(B)']),
    'GOOG': pd.Series([1133.43,36.05,335.83,0.87,31.44,380.64],
                      index=['Closing price','EPS',
                             'Shares Outstanding(M)',
                             'Beta','P/E','Market Cap(B)']),
    'FB': pd.Series([61.48,0.59,2450,104.93,150.92],
                    index=['Closing price','EPS',
                           'Shares Outstanding(M)',
                           'P/E', 'Market Cap(B)']),
    'YHOO': pd.Series([34.90,1.27,1010,27.48,0.66,35.36],
                      index=['Closing price','EPS',
                             'Shares Outstanding(M)',
                             'P/E','Beta', 'Market Cap(B)']),
    'TWTR':pd.Series([65.25,-0.3,555.2,36.23],
                     index=['Closing price','EPS',
                            'Shares Outstanding(M)',
                            'Market Cap(B)']),
    'AAPL':pd.Series([501.53,40.32,892.45,12.44,447.59,0.84],
                     index=['Closing price','EPS',
                            'Shares Outstanding(M)',
                            'P/E','Market Cap(B)','Beta'])
}
stockDF=pd.DataFrame(stockSummaries); stockDF

AMZN     GOOG       FB     YHOO    TWTR    AAPL
Beta                     0.52     0.87      NaN     0.66     NaN    0.84
Closing price          346.15  1133.43    61.48    34.90   65.25  501.53
EPS                      0.59    36.05     0.59     1.27   -0.30   40.32
Market Cap(B)          158.88   380.64   150.92    35.36   36.23  447.59
P/E                    589.80    31.44   104.93    27.48     NaN   12.44
Shares Outstanding(M)  459.00   335.83  2450.00  1010.00  555.20  892.45

In [40]:
stockDF=pd.DataFrame(stockSummaries,
                     index = ['Closing price','EPS',
                              'Shares Outstanding(M)',
                              'P/E', 'Market Cap(B)','Beta']);stockDF

AMZN     GOOG       FB     YHOO    TWTR    AAPL
Closing price          346.15  1133.43    61.48    34.90   65.25  501.53
EPS                      0.59    36.05     0.59     1.27   -0.30   40.32
Shares Outstanding(M)  459.00   335.83  2450.00  1010.00  555.20  892.45
P/E                    589.80    31.44   104.93    27.48     NaN   12.44
Market Cap(B)          158.88   380.64   150.92    35.36   36.23  447.59
Beta                     0.52     0.87      NaN     0.66     NaN    0.84

In [224]:
stockDF=pd.DataFrame(stockSummaries,
                     index=['Closing price','EPS',
                            'Shares Outstanding(M)',
                            'P/E', 'Market Cap(B)','Beta'],
                     columns=['FB','TWTR','SCNW']); stockDF

FB    TWTR SCNW
Closing price            61.48   65.25  NaN
EPS                       0.59   -0.30  NaN
Shares Outstanding(M)  2450.00  555.20  NaN
P/E                     104.93     NaN  NaN
Market Cap(B)           150.92   36.23  NaN
Beta                       NaN     NaN  NaN

In [225]:
stockDF.index

Index(['Closing price', 'EPS', 'Shares Outstanding(M)', 'P/E', 'Market Cap(B)',
       'Beta'],
      dtype='object')

In [226]:
stockDF.columns

Index(['FB', 'TWTR', 'SCNW'], dtype='object')

In [50]:
algos={'search':['DFS','BFS','Binary Search',
                 'Linear','ShortestPath (Djikstra)'],
       'sorting': ['Quicksort','Mergesort', 'Heapsort',
                   'Bubble Sort', 'Insertion Sort'],
       'machine learning':['RandomForest',
                           'K Nearest Neighbor',
                           'Logistic Regression',
                           'K-Means Clustering',
                           'Linear Regression']}

In [51]:
algoDF=pd.DataFrame(algos); algoDF

search         sorting     machine learning
0                      DFS       Quicksort         RandomForest
1                      BFS       Mergesort   K Nearest Neighbor
2            Binary Search        Heapsort  Logistic Regression
3                   Linear     Bubble Sort   K-Means Clustering
4  ShortestPath (Djikstra)  Insertion Sort    Linear Regression

In [52]:
algoDF.index = ['algo_1','algo_2','algo_3','algo_4','algo_5']; algoDF

search         sorting     machine learning
algo_1                      DFS       Quicksort         RandomForest
algo_2                      BFS       Mergesort   K Nearest Neighbor
algo_3            Binary Search        Heapsort  Logistic Regression
algo_4                   Linear     Bubble Sort   K-Means Clustering
algo_5  ShortestPath (Djikstra)  Insertion Sort    Linear Regression

In [54]:
algoDF['AAA'] = [1,2,3,4,5]; algoDF

search         sorting     machine learning  AAA
algo_1                      DFS       Quicksort         RandomForest    1
algo_2                      BFS       Mergesort   K Nearest Neighbor    2
algo_3            Binary Search        Heapsort  Logistic Regression    3
algo_4                   Linear     Bubble Sort   K-Means Clustering    4
algo_5  ShortestPath (Djikstra)  Insertion Sort    Linear Regression    5

In [49]:
pd.DataFrame(algos,index=['algo_1','algo_2','algo_3','algo_4','algo_5'])

search         sorting     machine learning
algo_1                      DFS       Quicksort         RandomForest
algo_2                      BFS       Mergesort   K Nearest Neighbor
algo_3            Binary Search        Heapsort  Logistic Regression
algo_4                   Linear     Bubble Sort   K-Means Clustering
algo_5  ShortestPath (Djikstra)  Insertion Sort    Linear Regression

In [55]:
memberData = np.zeros((4,),
                      dtype=[('Name','object'),
                             ('Age','i4'),
                             ('Weight','f4')])
memberData[:] = [('Sanjeev',37,162.4),
                 ('Yingluck',45,137.8),
                 ('Emeka',28,153.2),
                 ('Amy',67,101.3)]

In [56]:
memberDF=pd.DataFrame(memberData);memberDF

Name  Age      Weight
0   Sanjeev   37  162.399994
1  Yingluck   45  137.800003
2     Emeka   28  153.199997
3       Amy   67  101.300003

In [69]:
pd.DataFrame(memberData, index=['a','b','c','d'])

Name  Age      Weight
a   Sanjeev   37  162.399994
b  Yingluck   45  137.800003
c     Emeka   28  153.199997
d       Amy   67  101.300003

In [71]:
(memberDF.T)[0]

Name      Sanjeev
Age            37
Weight      162.4
Name: 0, dtype: object

DataFrame Operations

In [235]:
memberDF['Name']

0     Sanjeev
1    Yingluck
2       Emeka
3         Amy
Name: Name, dtype: object

In [236]:
memberDF['Height']=60;memberDF

Name  Age      Weight  Height
0   Sanjeev   37  162.399994      60
1  Yingluck   45  137.800003      60
2     Emeka   28  153.199997      60
3       Amy   67  101.300003      60

In [237]:
del memberDF['Height']; memberDF

Name  Age      Weight
0   Sanjeev   37  162.399994
1  Yingluck   45  137.800003
2     Emeka   28  153.199997
3       Amy   67  101.300003

In [238]:
memberDF['BloodType']='O'
memberDF

Name  Age      Weight BloodType
0   Sanjeev   37  162.399994         O
1  Yingluck   45  137.800003         O
2     Emeka   28  153.199997         O
3       Amy   67  101.300003         O

In [239]:
memberDF.pop('BloodType')

0    O
1    O
2    O
3    O
Name: BloodType, dtype: object

In [240]:
memberDF.insert(2,'isSenior',memberDF['Age']>60);memberDF

Name  Age  isSenior      Weight
0   Sanjeev   37     False  162.399994
1  Yingluck   45     False  137.800003
2     Emeka   28     False  153.199997
3       Amy   67      True  101.300003

In [74]:
memberDF['isSenior'] = memberDF['Age']>60;memberDF

Name  Age      Weight  isSenior
0   Sanjeev   37  162.399994     False
1  Yingluck   45  137.800003     False
2     Emeka   28  153.199997     False
3       Amy   67  101.300003      True

In [82]:
memberDF[['Name', 'isSenior','Age', 'Weight']]

Name  isSenior  Age      Weight
0   Sanjeev     False   37  162.399994
1  Yingluck     False   45  137.800003
2     Emeka     False   28  153.199997
3       Amy      True   67  101.300003

In [241]:
ore1DF=pd.DataFrame(np.array([[20,35,25,20],[11,28,32,29]]),
                    columns=['iron','magnesium','copper','silver'])
ore2DF=pd.DataFrame(np.array([[14,34,26,26],[33,19,25,23]]),
                    columns=['iron','magnesium','gold','silver'])
ore1DF+ore2DF

copper  gold  iron  magnesium  silver
0     NaN   NaN    34         69      46
1     NaN   NaN    44         47      52

In [244]:
ore1DF + pd.Series([25,25,25,25],
                   index=['iron','magnesium','copper','silver'])

iron  magnesium  copper  silver
0    45         60      50      45
1    36         53      57      54

In [245]:
np.sqrt(ore1DF)

iron  magnesium    copper    silver
0  4.472136   5.916080  5.000000  4.472136
1  3.316625   5.291503  5.656854  5.385165

Panel

In [88]:
USData=pd.DataFrame(np.array([[249.62, 8900],[282.16, 12680],[309.35, 14940]]),
                    columns=['Population(M)','GDP($B)'],index=[1990,2000,2010])
USData

Population(M)  GDP($B)
1990         249.62   8900.0
2000         282.16  12680.0
2010         309.35  14940.0

In [89]:
ChinaData=pd.DataFrame(np.array([[1133.68, 390.28],
                                 [ 1266.83, 1198.48],
                                 [1339.72, 6988.47]]),
                       columns=['Population(M)','GDP($B)'],
                       index=[1990,2000,2010])
ChinaData

Population(M)  GDP($B)
1990        1133.68   390.28
2000        1266.83  1198.48
2010        1339.72  6988.47